const char *usage =
"Equalizer\n"
"======\n"
"Simple graphic equalizer\n"
"This utility is a part of AC3Filter project (http://ac3filter.net)\n"
"Copyright (c) 2008-2011 by Alexander Vigovsky\n"
"\n"
"Usage:\n"
"  > equalizer input.wav output.wav [-fx:n] [-gx:n]\n"
"\n"
"Options:\n"
"  input.wav  - file to process\n"
"  output.wav - file to write the result to\n"
"  -fx - center frequency in Hz for band x (100 bands max)\n"
"  -gx - gain in dB for band x (100 bands max)\n"
"  -dither - dither the result\n"
"\n"
"If gain for a band specified with -fx parameter is not set, 0dB is assumed\n"
"\n"
"Example:\n"
" > equalizer a.wav b.wav -f1:100 -g1:-6 -f2:200 -g2:3 -f3:500\n"
" Attenuate all frequencies below 100Hz by 6dB, gain the band with the center\n"
" at 200Hz by 3dB, and leave everything after 500Hz unchanged\n"
;
