const char *usage =
"MPEG Program Stream demuxer\n"
"This utility is a part of AC3Filter project (http://ac3filter.net)\n"
"Copyright (c) 2007-2011 by Alexander Vigovsky);\n"
"\n"
"Usage:\n"
"  mpeg_demux file.mpg [-i] [-d | -p output_file [-s=x | -ss=x]]\n"
"  -i - file info (default)\n"
"  -d - demux to elementary stream\n"
"  -p - demux to pes stream\n"
"  -s=xx  - demux stream xx. Use '0x' prefix for hex values.\n"
"  -ss=xx - demux substream xx. Use '0x' prefix for hex values.\n"
"\n"
"Note: if stream/substream is not specified, demuxer will dump contents of all\n"
"packets found. This mode is useful to demux PES streams (not multiplexed) even\n"
"with format changes.\n"
;
